name: C++ CI with gcovr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install gcovr and g++
      run: |
        sudo apt update
        sudo apt install -y gcovr g++

    - name: Compile with coverage flags
      run: |
        g++ -fprofile-arcs -ftest-coverage -std=c++11 -o mi_programa main.cpp

    - name: Run program
      run: |
        ./mi_programa

    - name: Generate coverage report
      run: |
        gcovr --root . --exclude-directories test --html --html-details -o coverage.html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.html
