name: C++ CI con cobertura

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar gcovr y compiladores
      run: |
        sudo apt update
        sudo apt install -y lcov g++
        pip install gcovr

    - name: Compilar mi_programa.cpp con flags de cobertura
      run: |
        g++ -fprofile-arcs -ftest-coverage -o main main.cpp

    - name: Ejecutar el programa
      run: |
        ./mi_programa

    - name: Generar reporte de cobertura en HTML
      run: |
        gcovr --root . --html --html-details -o coverage.html

    - name: Subir artefacto del reporte de cobertura
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.html
